#version: '3.8'

services:
  app:
    build:
      context: .
    container_name: document-buddy-app
    volumes:
      - .:/workspace  # ✅ Mounts local directory
    working_dir: /workspace
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama:11434  # ✅ Connects to Ollama
      - QDRANT_HOST=http://qdrant:6333  # ✅ Ensures Qdrant is reachable
    depends_on:
#      qdrant:
#        condition: service_healthy
      ollama:
        condition: service_started

  qdrant:
    image: qdrant/qdrant:v1.8.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://qdrant:6333/healthz"]
#      interval: 10s
#      retries: 5
#      start_period: 10s
#      timeout: 5s

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # ✅ Persist downloaded models
    restart: always
    #entrypoint: ["/bin/sh", "-c", "if ! ollama list | grep -q 'llama3:8b'; then ollama pull llama3:8b; fi && exec ollama serve"]
    entrypoint: ["ollama", "serve"]

volumes:
  ollama_models:

