version: '3.8'

services:
  app:
    build:
      context: .
    container_name: document-buddy-app
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://host.docker.internal:11434  # 🔗 Native Ollama on host
      - QDRANT_HOST=http://host.docker.internal:6333   # 🔗 Native Qdrant on host
